### ISSUE TITLE
[Linux] Only root part sending

### ISSUE THREAD

**Issue by TheHellBox** [gavazquez/LunaMultiPlayer#48]
------------------------------------------------------------------------------

OS: Linux Debian 9.2

------------------------------------------------------------------------------

KSPVersion: 1.3.1

------------------------------------------------------------------------------

MODS (add link to download them): No

------------------------------------------------------------------------------

Steps to reproduce: Hm, use linux.

------------------------------------------------------------------------------

KSP Log: https://pastebin.com/C5ZWgsMu

------------------------------------------------------------------------------

Vessel: https://pastebin.com/D7nGKENR

------------------------------------------------------------------------------

output_log: No

------------------------------------------------------------------------------

**Comment by gavazquez** [comment]
Closed as being duplicate
